version: "1.0"
info:
  model: int-scaffold
packages:
- name: AbhkExternal2ndSeptProject
  gitServerName: abhk
  gitUrl: https://github.com/ak879753
  gitUsername: ak879753
  gitBranch: main
services:
- serviceName: project.abhkexternal2ndsept.integrations:Daf1
  packages:
  - name: AbhkExternal2ndSeptProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1120
